name: Sunho's Dev Blog
title: Sunho's Dev Blog
description: Dev Blog of Sunho Kim, a student developer.
tags:
  - blog
  - developer
  - student
  - software developer
  - software
  - developer blog
  - DevOps
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: sunhome243@gmail.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 
